Hotfix/no images
punkave/apostrophe-facebook pull request #2
Opened 2018-01-11 17:13 UTC by abea

The request URL is now only returning minimal information unless more is specified. This adds the fields to the request that are used in the module. I also edited the treatment of photo posts to insert `alt` tag information.

2018-01-11 19:28 UTC, plantainrain requested changes

2018-01-11 19:28 UTC, mtthwmnc commented on index.js
>      //fb.setAccessToken(access_token);
💣  if not needed

2018-01-11 19:28 UTC, mtthwmnc commented on index.js
> +        access_token + '&fields=source,name,created_time';
break out into separate lines each with own 'var' for readability

2018-01-11 19:45 UTC, abea commented
And updated. I almost went in on a full code cleanup, but that was a deep rabbit hole.

2018-01-16 15:31 UTC, bobclewell approved these changes
lgtm

2018-01-16 15:34 UTC, merged