Allows for disabling the server side API requests
punkave/apostrophe-facebook pull request #5
Opened 2019-01-29 21:05 UTC by abea

With significant changes to the Facebook API, I want to provide the opportunity to disable the server side requests to allow more complete client-side override.

2019-01-30 14:50 UTC, boutell submitted a review, later dismissed
Chuck a note in the README. Maybe call this apiDisabled.

2019-01-30 14:50 UTC, boutell commented
Otherwise fine

2019-01-30 17:03 UTC, abea commented
@boutell Updated and ready to quiet those staging notifications.

2019-01-31 22:09 UTC, boutell requested changes

2019-01-31 22:09 UTC, boutell commented on index.js
>    });
Is there a double close of `})` going on here?

2019-02-01 14:58 UTC, boutell approved these changes

2019-02-01 15:03 UTC, merged